- name: Demo on conditions
  hosts: localhost
  tasks:
    - name: print apple price
      ansible.builtin.debug:
        msg: apple price - 1$

    - name: print orange price
      ansible.builtin.debug:
        msg: orange price - 2$