- name: print used Memory
  hosts: localhost
  tasks:
    - name: Get Memory
      ansible.builtin.shell: free | grep Mem | xargs
      register: free

    - name: set a fact
      ansible.builtin.set_fact:
        msg: "{{free.stdout | split(' ') }}"

    - name: print free variable
      ansible.builtin.set_fact:
        total: "{{ FREE[1] }}"
        free: "{{ FREE[3] }}"
